### ISSUE TITLE
Should publish spring-boot-cf-service-broker artifact to maven central

### ISSUE THREAD

**Issue by poblin-orange** [cloudfoundry-community/spring-boot-cf-service-broker#21]
Cool project
Do you have any plan to publish the spring-boot-cf-service-broker to maven central ?
We would love to publish our internal cloudfoundry service broker, need an official base release to do so

**Comment by krujos** [comment]
Hi @poblin-orange, 
The artifacts are currently published on the spring.io milestone repo: 

http://repo.spring.io/libs-snapshot/org/cloudfoundry/spring-boot-cf-service-broker

Will that work for you? I agree that long term we probably want to be somewhere a little more "normal". I'll be making another update with the async API changes and can pursue publishing out to maven central or the main spring repo. 

Thanks!

**Comment by poblin-orange** [comment]
Hello @krujos
Yes we are currently using spring milestone to start. However, i have a doubt whether the broker should me managed as a spring extension (spring-milestone), or part of cloudfoundry community. 
Agree its a a global cloudfoundry community issue, maybe we should have a dedicated milestone repo for opensource effort on cf and shared process for final publication to maven repo.
