### ISSUE TITLE
custom CatalogService not being picked up

### ISSUE THREAD

**Issue by robertgmoss** [cloudfoundry-community/spring-boot-cf-service-broker#24]
I'm having a bit of trouble updating my broker to use `2.4.1`.  I have a `CatalogService` implementation class defined and marked with the `@Service` annotation.  This worked fine with `2.4.0`, but now when I try to run, it fails with this error:
```
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'beanCatalogService' defined in URL [jar:file:/home/robert/.m2/repository/org/cloudfoundry/spring-boot-cf-service-broker/2.4.1/spring-boot-cf-service-broker-2.4.1.jar!/org/cloudfoundry/community/servicebroker/service/BeanCatalogService.class]: Unsatisfied dependency expressed through constructor argument with index 0 of type [org.cloudfoundry.community.servicebroker.model.Catalog]: : No qualifying bean of type [org.cloudfoundry.community.servicebroker.model.Catalog] found for dependency:
expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {}; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [org.cloudfoundry.community.servicebroker.model.Catalog] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {}
```

Seems my `CatalogService` bean is not available when  `@ConditionalOnMissingBean(CatalogService.class)` in `ServiceBrokerAutoConfiguration` is checked.

**Comment by krujos** [comment]
@scottfrederick mind taking a look at this?

I'm a little surprised it worked reliably (although I'm pretty dumb about spring in the grand scheme of things)....  I think the root of it is the default service is making it to the `BeanFactory` before your implementation is. As I read the docs for `ConditionalOnMissingBean` it's dependent on the bean not being in the `BeanFactory` at the time it's loaded, which is appears to be non deterministic.  I suspect you could grab the  `BeanFactoryPostProcessor` and force your bean to be the only one loaded, but that sounds like all kids of headache.. Can you share your code and I'll see if I can find a more elegant solution in the framework? I've created a sample repro [here](https://github.com/krujos/spring-boot-broker-catalog-repro) but I want to make sure i've got it right before I go down a rabbit hole.

**Comment by robertgmoss** [comment]
Thanks, @krujos. Sure, the source is [here](https://github.com/cloudfoundry-community/brooklyn-service-broker/tree/async).

**Comment by robertgmoss** [comment]
@krujos @scottfrederick any further with this?

**Comment by krujos** [comment]
HI @robertgmoss I've not gotten a chance to dive in deeper yet. I hope to get to it this weekend. 
Thanks, 
Josh

**Comment by krujos** [comment]
@robertgmoss I was able to workaround the issue by excluding the starters config class in my test broker: 
```java
@SpringBootApplication
@EnableAutoConfiguration(exclude = { ServiceBrokerAutoConfiguration.class })
public class DemoApplication {
	private static Logger log = Logger.getLogger(DemoApplication.class);

	public static void main(String[] args) {
		SpringApplication.run(DemoApplication.class, args);
	}
}
```
The downside of this is that you have to specify your own `brokerApiVersion` as well as know the implementation details of the base project. @spgreenberg we should consider breaking the config class apart so folks can exclude with more granularity. 

I'd have thought `@AutoConfigBefore` would have worked here too, but I was unable to make it work and since explicitly excluding it felt more like the right thing (say what you mean and eliminate side effects) I didn't fuss with it much, but there may be something there if that suits your fancy. 

See the example code here: https://github.com/krujos/spring-boot-broker-catalog-repro

**Comment by scottfrederick** [comment]
@krujos @robertgmoss Apologies for not looking at this sooner, but I think I see what's going on here. 

The original error was `NoSuchBeanDefinitionException: No qualifying bean of type [org.cloudfoundry.community.servicebroker.model.Catalog] found`. The only place I can see a `Catalog` bean being injected is in the constructor for [BeanCatalogService](https://github.com/cloudfoundry-community/spring-boot-cf-service-broker/blob/master/src/main/java/org/cloudfoundry/community/servicebroker/service/BeanCatalogService.java). That class has an `@Service` annotation on it, which means that it is going to get discovered and instantiated via component scanning regardless of what [ServiceBrokerAutoConfiguration](https://github.com/cloudfoundry-community/spring-boot-cf-service-broker/blob/master/src/main/java/org/cloudfoundry/community/servicebroker/config/ServiceBrokerAutoConfiguration.java) does. Removing the `@Service` annotation from `BeanCatalogService` will let the auto-config class decide whether that bean should be added to the app context or not, and should eliminate this exception.

As the code is now, this exception is likely to be spurious, as it would depend on whether the `BeanCatalogService` or the custom catalog service was discovered first, which is non-deterministic.

**Comment by robertgmoss** [comment]
Thanks @scottfrederick that did the trick - I've submitted PR for that. 

@krujos Thanks - this work-around only partially worked since a component scan required to pick up the parent controllers still picked up the BeanCatalogService due to the `@Service` annotation.

**Comment by robertgmoss** [comment]
Any chance this change could be uploaded to the maven repo too?
