### ISSUE TITLE
Require Java 7

### ISSUE THREAD

**Issue by scottfrederick** [cloudfoundry-community/spring-boot-cf-service-broker#31]
This project doesn't currently enforce a minimum Java version for compilation or runtime. This project depends on Spring Boot, and [Boot defaults to Java 7](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#getting-started-system-requirements) without additional configuration. 

Are there any objections to making this project require Java 7 at a minimum?

What Java version have the published releases been compiled with?

cc: @spgreenberg @krujos

**Comment by krujos** [comment]
if we can't require 8 :).

**Comment by scottfrederick** [comment]
Fixed in https://github.com/cloudfoundry-community/spring-boot-cf-service-broker/commit/dbcb794e7320a872953542af6d64e1fb24452b6a.
