### ISSUE TITLE
service instance name is not passed from cloud controller to service broker. 

### ISSUE THREAD

**Issue by dave-chen** [cloudfoundry-community/spring-boot-cf-service-broker#32]
cf cs sample-service free my-service

The service instance name is not passed from cloud controller to service broker. We need to get the service instance name "my-service" from the CreateServiceInstanceRequest when performing the above CLI command.

**Comment by scottfrederick** [comment]
As you said, CC doesn't pass the service name to the service broker in the [provision request](http://docs.cloudfoundry.org/services/api.html#provisioning), so there is nothing this project can do to provide the information you are asking for to your broker. 

You referenced an issue in the CLI project, but that's not where the enhancement would need to be made. The CLI is already passing the service name to CC, but the service name is not part of the contract between CC and service brokers. It would be better to propose this change on the [cf-dev mailing list](https://lists.cloudfoundry.org/archives/list/cf-dev@lists.cloudfoundry.org/).

**Comment by dave-chen** [comment]
Thanks Scott! I posted on cf-dev as you suggested.
