### ISSUE TITLE
Proposal to move to cloudfoundry-incubator

### ISSUE THREAD

**Issue by robertgmoss** [cloudfoundry-community/spring-boot-cf-service-broker#33]
Guys,

Our service broker, which depends on this project, is in the cloudfoundry-incubator and we would very much like to see this project moved there too.  Would you be happy to make a proposal to the services PMC to this effect?

**Comment by scottfrederick** [comment]
@robertgmoss We have been discussing a counter-proposal to move this project to the [Spring Cloud](https://github.com/spring-cloud) org. This project, of course, relies heavily on Spring and Spring Boot, and might rely on Spring Cloud sub-projects for enhanced security and SSO features in the future. 

What are your goals for moving the project to cloudfoundry-incubator, and would those goals also be met by a move to spring-cloud?

**Comment by robertgmoss** [comment]
@scottfrederick We would like to see updates to the CF Service-Broker API integrated into this project as quickly as possible.  For example, we're currently building our broker from a personal [fork](https://github.com/robertgmoss/spring-boot-cf-service-broker/tree/async) to use the Asynchronous operations since these changes have not yet been merged (I know you made a clean up branch last month!).

Personally, I'd be happy to see it in Spring Cloud if it means we are not blocked waiting for updates to move our broker forward.

**Comment by robertgmoss** [comment]
@scottfrederick Any progress with this?

**Comment by scottfrederick** [comment]
@robertgmoss We are just doing a bit of legal due-diligence (w.r.t. CLAs and such as required for Spring Framework projects). We should be done soon.

**Comment by scottfrederick** [comment]
See https://github.com/spring-cloud/spring-cloud-cloudfoundry-service-broker
