### ISSUE TITLE
Async not merged into master

### ISSUE THREAD

**Issue by robertgmoss** [cloudfoundry-community/spring-boot-cf-service-broker#37]
Hi

Can the async-cleanup branch be merged yet?

**Comment by spiegela** [comment]
Related question:  Does the async-cleanup branch bring this project up to [service broker API version 2.7](http://docs.cloudfoundry.org/services/api.html)?

**Comment by scottfrederick** [comment]
The async-cleanup branch has been merged. 

I'm not sure about API version 2.7 compatibility. Let's open a new issue for that.
