### ISSUE TITLE
Why isn't the service name provided?

### ISSUE THREAD

**Issue by arnaudruffin** [cloudfoundry-community/spring-boot-cf-service-broker#39]
Hi

When creating a service instance with Cloud Foundry CLI, I can see that the parameter "name" is provided to the service broker (and returned in the response).
```
REQUEST: [2015-11-19T16:54:18+01:00]
POST /v2/service_instances?accepts_incomplete=true HTTP/1.1
Host: api.xxx.xxx
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Content-Type: application/json
User-Agent: go-cli 6.12.4-b4b6af1 / darwin

{"name":"THIS_IS_THE_SERVICE_NAME","space_guid":"2d745a4b-67e3-4398-986e-2adbcf8f7ec9","service_plan_guid":"0179eda6-bbcb-408a-aff9-d21d748056dc","parameters":{"myparam":"buce"}}
````

Don't you think we should make it available in the `CreateServiceInstanceRequest` and `ServiceInstance` objects?

I can submit a pull request if you wish.

**Comment by antechrestos** [comment]
Sadly the service name is not sent to the application that implements the service broker api.

Logging an incoming create service instance request gave me this:
```
2015-11-23T16:47:07.12+0100 [App/0]      OUT DEBUG o.s.w.f.CommonsRequestLoggingFilter(55) - After request [uri=/v2/service_instances/f10171e3-7c92-4a71-8f63-72358cc0747a?accepts_incomplete=true;client=192.168.26.6;user=oto;payload={"service_id":"xxx","plan_id":"xx-xx-xx-xx-xx","organization_guid":"yy-yy-yy-yy","space_guid":"zz-zz-zz-zz-zz","parameters":{"inactivity":"PT15M"}}]
```
And nothing more :crying_cat_face:

**Comment by scottfrederick** [comment]
If you look at the [service broker API](http://docs.cloudfoundry.org/services/api.html#provisioning), you will see that the service instances name is not passed to the broker. The name of a service instance can change after it is created, so it would be a bad idea for a broker or any resources created by the broker to persist the name. The GUID is the only unique identifier for the service instance.
